version: 2

# Path to your Sphinx configuration file
sphinx:
  configuration: docs/source/conf.py

# Python environment setup
python:
  install:
    - method: pip
      path: .          
    - requirements: requirements.txt
